[package]
name = "miniserde"
version = "0.1.11"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Data structure serialization library with several opposite design goals from Serde."
repository = "https://github.com/dtolnay/miniserde"
documentation = "https://docs.rs/miniserde"
readme = "README.md"
edition = "2018"

[dependencies]
itoa = "0.4.3"
mini-internal = { version = "=0.1.11", path = "derive" }
ryu = "1.0"

[dev-dependencies]
automod = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[workspace]
members = ["derive", "mini-bench"]
